<?php

/**
 * $country places/cities/municipalities/districts
 * - $count places/cities/municipalities/districts
 * 
 * Source: 
 * - [Please add the source(s) link(s) to check the list of places]
 * 
 * @author  Your Name Here <yourname@here.com> | https://yourwebsite.com
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

// Replace 'XX' code for your Country Code. E.g. 'NG' for Nigeria, 'CO' for Colombia, 'VE' for Venezuela, etc.
// Please refer to WooCommerce country codes : https://github.com/woocommerce/woocommerce/blob/master/i18n/countries.php
$places['QA'] = array(
  // Replace 'AA' code with the code of the State you want to mapping this places  
  'DA' => array(
    // Add all the places of this State, one place per line
        'Ad Dawhah al Jadidah',
        'Al Bidda',
        'Al Dafna',
        'Al Egla',
        'Al Hilal',
        'Al Jasrah',
        'Al Kharayej',
        'Al Khulaifat',
        'Al Mansoura',
        'Al Markhiyah',
        'Al Mearad',
        'Al Messila',
        'Al Mirqab',
        'Al Najada',
        'Al Qassar',
        'Al Rufaa',
        'Al Sadd',
        'Al Seej',
        'Al Souq',
        'Al Tarfa',
        'Al Thumama (Doha)',
        'As Salatah',
        'Barahat Al Jufairi',
        'Dahl Al Hamam',
        'Doha International Airport',
        'Doha Port',
        'Duhail',
        'Fereej Abdel Aziz',
        'Fereej Al Asmakh',
        'Fereej Al Nasr',
        'Fereej Bin Durham',
        'Fereej Bin Mahmoud',
        'Fereej Bin Omran',
        'Fereej Kulaib',
        'Fereej Mohammed Bin Jassim',
        'Hamad Medical City',
        'Hazm Al Markhiya',
        'Industrial Area',
        'Jabal Thuaileb',
        'Jelaiah',
        'Jeryan Nejaima',
        'Lejbailat',
        'Lekhwair',
        'Leqtaifiya (West Bay Lagoon)',
        'Madinat Khalifa North',
        'Madinat Khalifa South',
        'Mushayrib',
        'Najma',
        'New Al Hitmi',
        'New Al Mirqab',
        'New Salata',
        'Nuayjah',
        'Old Airport',
        'Old Al Ghanim',
        'Old Al Hitmi',
        'Onaiza',
        'Ras Abu Aboud',
        'Rawdat Al Khail',
        'Rumeilah',
        'The Pearl',
        'Umm Ghuwailina',
        'Umm Lekhba',
        'Wadi Al Banat',
        'Wadi Al Sail',
  ),
  'ZA' => array(
        'Al Daayen',
        'Al Ebb',
        'Al Kheesa',
        'Al Masrouhiya',
        'Al Sakhama',
        'Jeryan Jenaihat',
        'Leabaib',
        'Lusail',
        'Rawdat Al Hamama',
        'Umm Qarn',
        'Wadi Al Wasaah',
        'Wadi Lusail',
  ),
  'KH' => array(
        'Al Ghuwariyah',
        'Al Jeryan',
        'Al Khor',
        'Al Thakhira',
        'Ras Lafan',
        'Simaisma',
        'Umm Birka',

  ),
  'RA' => array(
        'Abu Hamour',
        'Abu Samra',
        'Ain Khaled',
        'Al Aziziya',
        'Al Gharrafa',
        'Al Luqta',
        'Al Mamoura',
        'Al Nasraniya',
        'Al Sailiya',
        'Al Shagub',
        'Al Themaid',
        'Al Utouriya',
        'Al Waab',
        'Al Wajba',
        'Al-Shahaniya',
        'Baaya',
        'Bani Hajer',
        'Bu Samra',
        'Bu Sidra',
        'Dukhan',
        'Fereej Al Amir',
        'Fereej Al Asiri',
        'Fereej Al Manaseer',
        'Fereej Al Murra',
        'Fereej Al Soudan',
        'Fereej Al Zaeem',
        'Gharrafat Al Rayyan',
        'Izghawa (Al Rayyan)',
        'Lebday',
        'Lijmiliya',
        'Luaib',
        'Mebaireek',
        'Mehairja',
        'Mesaimeer',
        'Muaither',
        'Muraikh',
        'New Al Rayyan',
        'New Fereej Al Ghanim',
        'New Fereej Al Khulaifat',
        'Old Al Rayyan',
        'Rawdat Egdaim',
        'Rawdat Rashed',
        'Sawda Natheel',
        'Umm Bab',
  ),  
  'MS' => array(
        'Abu Dhalouf',
        'Ain Sinan',
        'Al Zubarah',
        'Ar Ruays',
        'Fuwayrit',
        'Madinat Al Kaaban',
        'Madinat ash Shamal',
  ),
  'WA' => array(
        'Al Karaana',
        'Al Kharrara',
        'Al Mashaf',
        'Al Thumama (Al Wakrah)',
        'Al Wakrah',
        'Al Wukair',
        'Khawr al Udayd',
        'Mesaieed',
        'Mesaieed Industrial Area',
        'Shagra',
  ),  
  'US' => array(
        'Al Kharaitiyat',
        'Bu Fasseela',
        'Izghawa (Umm Salal)',
        'Umm Salal Ali',
        'Umm Salal Mohammed',
  ),  
);
